apiVersion: v2
name: aviso-chart
description: A Helm chart for Aviso Server - streaming notification service
type: application
version: 0.3.0
appVersion: "0.4.0"
keywords:
  - notifications
  - streaming
  - sse
  - rust
icon: https://github.com/ecmwf/logos/blob/main/logos/aviso/aviso_light.svg

maintainers:
  - name: Samet Demir
  - name: James Hawkes

sources:
  - https://github.com/ecmwf/aviso-server

home: https://github.com/ecmwf/aviso-server

dependencies:
  - name: nats
    version: 2.12.4
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  - name: auth-o-tron-chart
    version: 0.3.0
    repository: oci://eccr.ecmwf.int/auth-o-tron
    condition: auth-o-tron.enabled
    alias: auth-o-tron
