{
 "title": "Aviso NATS / JetStream",
 "description": "NATS JetStream Dashboard",
 "tags": [
  "aviso",
  "nats",
  "jetstream"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nats_varz_connections, namespace)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(nats_varz_connections{namespace=~\"$namespace\"}, server_id)"
    }
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values(nats_stream_last_seq{namespace=~\"$namespace\"}, stream_name)"
    }
   },
   {
    "name": "consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(nats_consumer_num_pending{namespace=~\"$namespace\"}, consumer_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{namespace=~\"$namespace\",server_id=~\"$server\"})/sum(nats_varz_jetstream_config_max_storage{namespace=~\"$namespace\",server_id=~\"$server\"})"
    },
    {}
   ]
  },
  {
   "title": "Total Storage Used",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{namespace=~\"$namespace\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_connections{namespace=~\"$namespace\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Max Storage",
   "type": "stat",
   "gridPos": { "x": 8, "y": 3, "w": 8, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_config_max_storage{namespace=~\"$namespace\",server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "x": 16, "y": 3, "w": 8, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_server_total_consumers{namespace=~\"$namespace\",server_id=~\"$server\"})"
    }
   ]
  },
  { "title": "Stream metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Stream data size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_bytes{namespace=~\"$namespace\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream message count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_messages{namespace=~\"$namespace\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Message Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_stream_last_seq{namespace=~\"$namespace\",server_id=~\"$server\",stream_name=~\"$stream\"}[$__rate_interval])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Messages per second (++/--)",
   "type": "timeseries",
   "description": "Messages added & processed per minute per consumer",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_num_pending{namespace=~\"$namespace\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}[$__rate_interval])+rate(nats_consumer_delivered_consumer_seq{namespace=~\"$namespace\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}} +"
    },
    {
     "expr": "- sum(rate(nats_consumer_delivered_consumer_seq{namespace=~\"$namespace\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\",consumer_name=~\"$consumer\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}} -"
    }
   ]
  },
  {
   "title": "Total delivered messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_delivered_consumer_seq{namespace=~\"$namespace\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Pending messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_pending{namespace=~\"$namespace\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Acks Pending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_ack_pending{namespace=~\"$namespace\",server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  }
 ]
}