{{- if .Values.authSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authSecret.name }}
  labels:
    {{- include "aviso-server.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.authSecret.jwtSecret | b64enc | quote }}
{{- end }}
