{{/*
SPDX-FileCopyrightText: 2026 European Centre for Medium-Range Weather Forecasts (ECMWF)
SPDX-License-Identifier: Apache-2.0
*/}}
{{- include "aviso-server.validateIngress" . -}}
{{- $config := deepCopy .Values.config -}}
{{- $_ := set $config.application "base_url" (include "aviso-server.applicationBaseURL" .) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aviso-server.fullname" . }}-config
  labels:
    {{- include "aviso-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml $config | nindent 4 }}
